# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Test Documentation
site_url: https://dimasmith.github.io/mkdocs-tutorial/
repo_url: https://github.com/dimasmith/mkdocs-tutorial
copyright: Copyright 2025 Dmytro Kovalchuk
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
  features:
    - content.code.copy
  icon:
    annotation: material/plus-circle

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

nav:
  - Architecture:
      - Roadmap: architecture/roadmap.md
      - Views:
          - Catalog: architecture/views/views.md
          - System Context: architecture/views/context-view.md
          - Diagrams: architecture/views/diagrams.md
          - Implementation: architecture/views/example.md
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
