# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Test Documentation
site_url: https://dimasmith.github.io/mkdocs-tutorial/
repo_url: https://github.com/dimasmith/mkdocs-tutorial
copyright: Copyright 2025 Dmytro Kovalchuk
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode

plugins:
  - search

nav:
  - Architecture:
      - Roadmap: architecture/roadmap.md
      - Views:
          - Catalog: architecture/views/views.md
          - System Context: architecture/views/context-view.md
          - Interaction: architecture/views/interaction.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
